# Generated by Django 5.2.6 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoimagem',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(default='', upload_to='produtos/images'),
            preserve_default=False,
        ),
    ]
