# Generated by Django 5.2.6 on 2025-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovideo',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
