# Generated by Django 5.2.6 on 2025-10-13 11:03

import apps.produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produtoimagem_url_imagem_produtoimagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovideo',
            name='video',
            field=models.FileField(default='', storage=apps.produtos.models.MediaStorage(), upload_to='produtos/videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(storage=apps.produtos.models.MediaStorage(), upload_to='produtos/images'),
        ),
    ]
