# Generated by Django 5.2.6 on 2025-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtovideo_video_alter_produtoimagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovideo',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
