<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-21 15:01
=======
# Generated by Django 5.2.6 on 2025-10-21 11:21
>>>>>>> main

import apps.produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtovideo_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovideo',
            name='url_video',
        ),
        migrations.AlterField(
            model_name='produtovideo',
            name='video',
            field=models.FileField(storage=apps.produtos.models.MediaStorage(), upload_to=apps.produtos.models.video_upload_path),
        ),
    ]
