# Generated by Django 5.2.6 on 2025-09-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='codigo_afiliado',
            new_name='codigo_sicio',
        ),
    ]
