# Generated by Django 5.2.6 on 2025-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_codigo_afiliado_socio_codigo_sicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='codigo_sicio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
