# Generated by Django 5.2.6 on 2025-09-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_socio_codigo_sicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='codigo_sicio',
            new_name='codigo_socio',
        ),
    ]
