# Generated by Django 5.2.6 on 2025-10-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_codigo_sicio_socio_codigo_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='bi_frente',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='bi_verso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='socio',
            name='codigo_socio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
