# Generated by Django 5.2.6 on 2025-10-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_codigo_sicio_socio_codigo_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='bi_frente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='bi_verso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
